version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: django
      POSTGRES_DB: django
    ports:
      - 5555:5432

